const dramas = [
    {
        id: 1,
        title: "死神与少年",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["小野塚小町", "圣白莲", "命莲", "八意永琳", "射命丸文", "琪露诺", "大妖精", "多多良小伞", "娜兹玲", "村纱水蜜", "云居一轮", "幽谷响子", "河城荷取", "水桥帕露西", "封兽鵺", "若鹭姬", "露米娅", "上白泽慧音", "星熊勇仪", "伊吹萃香", "铃仙", "博丽灵梦", "魂魄妖梦", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBa1NoKDTH1nkAHgOwAHzhma",
        translatedUrl: "https://space.bilibili.com/12621850/lists/4882608",
        description: "你是我活过的证明。",
        thumbnail: "https://free.picui.cn/free/2026/02/02/69806ad0158cd.jpg",
        dateAdded: "2023-06-18"
    },
    {
        id: 2,
        title: "幻想死洛谭",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["上白泽慧音", "琪露诺", "大妖精", "易者", "藤原妹红", "豫母都日狭美", "三头慧之子", "秦心", "比那名居天子", "永江衣玖", "犬走椛", "绵月依姬", "少名针妙丸", "稀神探女", "菅牧典", "铃仙", "芙兰朵露", "小野塚小町", "八意永琳", "丰聪耳神子", "八云蓝", "魂魄妖梦", "河城荷取", "星熊勇仪", "水桥帕露西", "射命丸文"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBZ63LCFxhe0uDIma4lgCMfC",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5066012",
        description: "死而未绝，络续不绝之缘。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9b3b3c.jpg",
        dateAdded: "2024-08-24"
    },
    {
        id: 3,
        title: "幻想心狼殿",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["古明地觉", "古明地恋", "魂魄妖梦", "芙兰朵露", "灵乌路空", "火焰猫燐", "藤原妹红"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBaXcAkHQes8-dkINhSlG-Aj",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6561665",
        description: "一群变态似乎在拯救世界。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9c7f83.jpg",
        dateAdded: "2025-08-17"
    },
    {
        id: 4,
        title: "騒がしすぎて怖くない夜廻三",
        author: "ささきの茶釜",
        translator: "",
        tags: [],
        isTranslated: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBYrCViDpMBfFOEy1R4xNi1t",
        translatedUrl: "",
        description: "夜明けまでに、呪いを解く方法を思い出せ。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9f2bff.jpg",
        dateAdded: "2022-08-10"
    },
    {
        id: 5,
        title: "吸血鬼と同棲⁉",
        author: "ねんねまるゆっくり",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "博丽灵梦", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL4PMLGSCaH8AF_vC-FcV9DTDU5XPCatxG",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6267690",
        description: "莫名其妙就要和吸血鬼同居了！？",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9ea961.jpg",
        dateAdded: "2020-05-29"
    },
    {
        id: 6,
        title: "红月夜的契约——与蕾米莉亚的彻夜醉迷",
        author: "不知火桃",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "古明地觉"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLFU-QWGTBq-4SsfGQuJBNzmvZtTzN3FoJ",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6324095",
        description: "学校的优等生竟和吸血鬼夜游！？",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9caf1f.jpg",
        dateAdded: "2022-09-09"
    },
    {
        id: 7,
        title: "Bunny girl",
        author: "MISAKI 3518",
        translator: "寄遗忘之物于流年",
        tags: ["铃仙"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=ienoNid46dM&list=PLPIDlOi7aH3EiGs9HnU3Rg52r4j587qsI&index=6",
        translatedUrl: "https://www.bilibili.com/video/BV16A6QBCEqD/?vd_source=29215d7e01e2e3b79461f647961a787f",
        description: "与铃仙在酒吧的小故事",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d4bbb3958.jpg",
        dateAdded: "2025-06-20"
    }
];