const dramas = [
    {
        id: 1,
        title: "死神与少年",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["小町"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=Zth3g7mHbp0&t=305s",
        translatedUrl: "https://space.bilibili.com/12621850/lists/4882608",
        description: "海上小岛怪谈故事，小町是女主角。",
        thumbnail: "images/1.jpg",
        dateAdded: "2026-02-02"
    },
    // {
    //     id: 2,
    //     title: "紅魔館のパーティー",
    //     author: "作者B",
    //     translator: "译者B",
    //     tags: ["红魔馆", "蕾米莉亚", "芙兰朵露", "搞笑"],
    //     isTranslated: true,
    //     originalUrl: "https://www.youtube.com/watch?v=example2",
    //     translatedUrl: "https://www.bilibili.com/video/BV1example2",
    //     description: "红魔馆的派对，大小姐和咲夜的日常。",
    //     thumbnail: "https://via.placeholder.com/400x225/764ba2/ffffff?text=紅魔館のパーティー",
    //     dateAdded: "2026-01-20"
    // },
    // {
    //     id: 3,
    //     title: "永遠亭の実験",
    //     author: "作者C",
    //     translator: null,
    //     tags: ["永远亭", "辉夜", "铃仙", "科学"],
    //     isTranslated: false,
    //     originalUrl: "https://www.youtube.com/watch?v=example3",
    //     translatedUrl: null,
    //     description: "永远亭的疯狂实验，辉夜公主的奇思妙想。",
    //     thumbnail: "https://via.placeholder.com/400x225/10b981/ffffff?text=永遠亭の実験",
    //     dateAdded: "2026-01-25"
    // },
    // {
    //     id: 4,
    //     title: "地霊殿の温泉",
    //     author: "作者D",
    //     translator: "译者D",
    //     tags: ["地灵殿", "古明地", "觉", "温泉"],
    //     isTranslated: true,
    //     originalUrl: "https://www.youtube.com/watch?v=example4",
    //     translatedUrl: "https://www.bilibili.com/video/BV1example4",
    //     description: "地灵殿的温泉时间，古明地姐妹的温馨时刻。",
    //     thumbnail: "https://via.placeholder.com/400x225/f59e0b/ffffff?text=地霊殿の温泉",
    //     dateAdded: "2026-02-01"
    // },
    // {
    //     id: 5,
    //     title: "命蓮寺の修行",
    //     author: "作者E",
    //     translator: null,
    //     tags: ["命莲寺", "圣白莲", "命莲", "修行"],
    //     isTranslated: false,
    //     originalUrl: "https://www.youtube.com/watch?v=example5",
    //     translatedUrl: null,
    //     description: "命莲寺的修行日常，圣白莲的教导。",
    //     thumbnail: "https://via.placeholder.com/400x225/ef4444/ffffff?text=命蓮寺の修行",
    //     dateAdded: "2026-02-02"
    // },
    // {
    //     id: 6,
    //     title: "霊夢と魔理沙の冒険",
    //     author: "作者F",
    //     translator: "译者F",
    //     tags: ["冒险", "灵梦", "魔理沙", "搞笑"],
    //     isTranslated: true,
    //     originalUrl: "https://www.youtube.com/watch?v=example6",
    //     translatedUrl: "https://www.bilibili.com/video/BV1example6",
    //     description: "灵梦和魔理沙的奇妙冒险，解决异变的故事。",
    //     thumbnail: "https://via.placeholder.com/400x225/8b5cf6/ffffff?text=霊夢と魔理沙の冒険",
    //     dateAdded: "2026-01-10"
    // },
    // {
    //     id: 7,
    //     title: "八雲紫のいたずら",
    //     author: "作者G",
    //     translator: null,
    //     tags: ["八云紫", "紫", "恶作剧", "境界"],
    //     isTranslated: false,
    //     originalUrl: "https://www.youtube.com/watch?v=example7",
    //     translatedUrl: null,
    //     description: "八云紫的恶作剧，妖怪贤者的日常。",
    //     thumbnail: "https://via.placeholder.com/400x225/ec4899/ffffff?text=八雲紫のいたずら",
    //     dateAdded: "2026-01-18"
    // },
    // {
    //     id: 8,
    //     title: "妖夢の修行日記",
    //     author: "作者H",
    //     translator: "译者H",
    //     tags: ["魂魄妖梦", "半灵", "修行", "冥界"],
    //     isTranslated: true,
    //     originalUrl: "https://www.youtube.com/watch?v=example8",
    //     translatedUrl: "https://www.bilibili.com/video/BV1example8",
    //     description: "魂魄妖梦的修行日记，半灵的成长故事。",
    //     thumbnail: "https://via.placeholder.com/400x225/06b6d4/ffffff?text=妖夢の修行日記",
    //     dateAdded: "2026-01-22"
    // },
    // {
    //     id: 9,
    //     title: "萃香の宴会",
    //     author: "作者I",
    //     translator: "译者I",
    //     tags: ["伊吹萃香", "宴会", "酒", "热闹"],
    //     isTranslated: true,
    //     originalUrl: "https://www.youtube.com/watch?v=example9",
    //     translatedUrl: "https://www.bilibili.com/video/BV1example9",
    //     description: "伊吹萃香的宴会，妖怪的狂欢派对。",
    //     thumbnail: "https://via.placeholder.com/400x225/f97316/ffffff?text=萃香の宴会",
    //     dateAdded: "2026-01-28"
    // },
    // {
    //     id: 10,
    //     title: "華扇の道場",
    //     author: "作者J",
    //     translator: null,
    //     tags: ["茨木华扇", "道场", "武术", "修行"],
    //     isTranslated: false,
    //     originalUrl: "https://www.youtube.com/watch?v=example10",
    //     translatedUrl: null,
    //     description: "茨木华扇的道场，武术的传承。",
    //     thumbnail: "https://via.placeholder.com/400x225/84cc16/ffffff?text=華扇の道場",
    //     dateAdded: "2026-01-30"
    // }
];