const dramas = [
    {
        id: 1,
        title: "这里是幻想高中话剧部！",
        author: "OKOME",
        translator: "一脚踢飞毛布",
        tags: ["秋静叶", "博丽灵梦", "鬼人正邪", "上白泽慧音", "八云紫", "魂魄妖忌", "魂魄妖梦", "雾雨魔理沙", "西行寺幽幽子"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL-pkvuGg-eTBtbPiC-dhheSrl0GaAeifd",
        translatedUrl: "https://space.bilibili.com/33819012/lists/6789016",
        description: "来演话剧吧！博丽同学！",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982e5c6bfe56.jpg",
        dateAdded: "2025-02-10"
    },
    {
        id: 2,
        title: "死神与少年",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["小野塚小町", "圣白莲", "命莲", "八意永琳", "射命丸文", "琪露诺", "大妖精", "多多良小伞", "娜兹玲", "村纱水蜜", "云居一轮", "幽谷响子", "河城荷取", "水桥帕露西", "封兽鵺", "若鹭姬", "露米娅", "上白泽慧音", "星熊勇仪", "伊吹萃香", "铃仙", "博丽灵梦", "魂魄妖梦", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBa1NoKDTH1nkAHgOwAHzhma",
        translatedUrl: "https://space.bilibili.com/12621850/lists/4882608",
        description: "你是我活过的证明。",
        thumbnail: "https://free.picui.cn/free/2026/02/02/69806ad0158cd.jpg",
        dateAdded: "2023-06-18"
    },
    {
        id: 3,
        title: "幻想死洛谭",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["上白泽慧音", "琪露诺", "大妖精", "易者", "藤原妹红", "豫母都日狭美", "三头慧之子", "秦心", "比那名居天子", "永江衣玖", "犬走椛", "绵月依姬", "少名针妙丸", "稀神探女", "菅牧典", "铃仙", "芙兰朵露", "小野塚小町", "八意永琳", "丰聪耳神子", "八云蓝", "魂魄妖梦", "河城荷取", "星熊勇仪", "水桥帕露西", "射命丸文"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBZ63LCFxhe0uDIma4lgCMfC",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5066012",
        description: "死而未绝，络续不绝之缘。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9b3b3c.jpg",
        dateAdded: "2024-08-24"
    },
    {
        id: 4,
        title: "幻想心狼殿",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["古明地觉", "古明地恋", "魂魄妖梦", "芙兰朵露", "灵乌路空", "火焰猫燐", "藤原妹红"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBaXcAkHQes8-dkINhSlG-Aj",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6561665",
        description: "一群变态似乎在拯救世界。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9c7f83.jpg",
        dateAdded: "2025-08-17"
    },
    {
        id: 5,
        title: "騒がしすぎて怖くない夜廻三",
        author: "ささきの茶釜",
        translator: "",
        tags: ["魂魄妖梦", "芙兰朵露", "十六夜咲夜", "洩矢诹访子", "博丽灵梦", "东风谷早苗", "雾雨魔理沙", "森近霖之助", "上白泽慧音", "蕾米莉亚", "爱丽丝"],
        isTranslated: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBYrCViDpMBfFOEy1R4xNi1t",
        translatedUrl: "",
        description: "夜明けまでに、呪いを解く方法を思い出せ。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9caf1f.jpg",
        dateAdded: "2022-08-10"
    },
    {
        id: 6,
        title: "幻想怪異録",
        author: "ラングリィ",
        translator: "就是很一般",
        tags: ["十六夜咲夜", "蕾米莉亚", "芙兰朵露", "博丽灵梦", "雾雨魔理沙", "水桥帕露西", "藤原妹红"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLiZP5uzNOuqyLnTRnyb4ZT5LuoVlBxnyE",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5251532",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/03/69821120d59cb.jpg",
        dateAdded: "2021-03-24"
    },
    {
        id: 7,
        title: "东方海龟汤",
        author: "みつば【mituba】",
        translator: "就是很一般",
        tags: ["博丽灵梦", "雾雨魔理沙", "东风谷早苗", "十六夜咲夜", "魂魄妖梦"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLmc6eO_qCE4najTjdUCtXDa0Agx8tzDON",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6172948",
        description: "大家听说过水平思考谜题吗？\n也被称为\"海龟汤\"呢。",
        thumbnail: "https://free.picui.cn/free/2026/02/03/69821120e2371.jpg",
        dateAdded: "2026-02-03"
    },
    {
        id: 8,
        title: "欠了100亿的我被蕾米莉亚用100元买下了",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["蕾米莉亚", "芙兰朵露", "十六夜咲夜"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLeIWlGzrNsQUtLMAjpHAw4AN2U9j6-xwn",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5962069",
        description: "你听说过百元行的故事吗？",
        thumbnail: "https://free.picui.cn/free/2026/02/03/698211211d834.jpg",
        dateAdded: "2024-07-25"
    },
    {
        id: 9,
        title: "那些年我与小石头的恋爱攻防战",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["古明地恋"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcclvKXISMZ2fy8POHkEd3sSA",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5264242",
        description: "短篇故事，大概100集",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6982161b1d56a.jpg",
        dateAdded: "2024-07-31"
    },
    {
        id: 10,
        title: "创世神似乎在自己的世界挑战强者的样子",
        author: "DAIゆっくり",
        translator: "就是很一般",
        tags: ["八云紫", "蕾米莉亚", "芙兰朵露", "博丽灵梦", "古明地恋", "十六夜咲夜", "犬走椛", "雾雨魔理沙", "洩矢诹访子", "西行寺幽幽子", "魂魄妖梦", "上白泽慧音", "秦心"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL2h240ZAgAYEaeVipLKlDJaK-FswRZMuu",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5697073",
        description: "非常有意思的战斗向茶剧",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6982161b519de.jpg",
        dateAdded: "2024-03-07"
    },
    {
        id: 11,
        title: "冷漠读心男幻想入",
        author: "白熱の親指",
        translator: "就是很一般",
        tags: ["博丽灵梦", "雾雨魔理沙", "露米娅", "东风谷早苗", "古明地恋", "八云紫", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=boGrjUJpBVo",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5116051",
        description: "一个在油管上比较有趣的幻想入系列，但有着原创主人公、角色暴力表现。觉得不OK的慎入",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6982161ba71d8.jpg",
        dateAdded: "2024-12-06"
    },
    {
        id: 12,
        title: "河童世界谚语剧场",
        author: "須方のさんちゃん工房",
        translator: "就是很一般",
        tags: ["纯狐", "八云蓝", "小恶魔", "雾雨魔理沙", "神绮", "摩多罗隐岐奈", "宫出口瑞灵", "维缦浅间", "河城荷取", "依神女苑", "八云紫", "易者", "朱鹭子", "渡里妮娜", "洩矢诹访子"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=tL5lu9jG9m8",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5104404",
        description: "世界谚语科普",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982d83f1e9d1.jpg",
        dateAdded: "2022-08-13"
    },
    {
        id: 13,
        title: "天才的我被IQ9的后辈琪露诺告白了",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["琪露诺", "大妖精", "露米娅"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=6cME-im2kDE",
        translatedUrl: "https://space.bilibili.com/12621850/lists/7228361",
        description: "这是啥子角色？",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982d83f047d8.jpg",
        dateAdded: "2021-12-27"
    },
    {
        id: 14,
        title: "爱上可爱妖梦.....但是",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["魂魄妖梦"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPccn24qH-xfKfS2XQTJY30Fuu",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6626365",
        description: "魂魄妖梦，你毁了我的性取向",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982d83f0bb27.jpg",
        dateAdded: "2019-02-16"
    },
    {
        id: 15,
        title: "红月夜的契约——与蕾米莉亚的彻夜醉迷",
        author: "不知火桃",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "古明地觉"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLFU-QWGTBq-4SsfGQuJBNzmvZtTzN3FoJ",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6324095",
        description: "学校的优等生竟和吸血鬼夜游！？",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9f2bff.jpg",
        dateAdded: "2022-09-09"
    },
    {
        id: 16,
        title: "吸血鬼と同棲⁉",
        author: "ねんねまるゆっくり",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "博丽灵梦", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL4PMLGSCaH8AF_vC-FcV9DTDU5XPCatxG",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6267690",
        description: "莫名其妙就要和吸血鬼同居了！？",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d3f9ea961.jpg",
        dateAdded: "2020-05-29"
    },
    {
        id: 17,
        title: "东方永梦樱",
        author: "みつば【mituba】",
        translator: "Baby_2016",
        tags: ["西行寺幽幽子", "八云紫", "魂魄妖梦", "博丽灵梦", "十六夜咲夜", "雾雨魔理沙", "东风谷早苗", "蕾米莉亚", "芙兰朵露", "宫古芳香", "铃仙", "绵月依姬", "藤原妹红", "八云蓝", "上白泽慧音", "古明地恋", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLmc6eO_qCE4nYR7tYmTsppAF1CTxhcrTP",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6449310",
        description: "佛前樱散祈缘契，愿渡来生共世人。",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982deaa68f9e.jpg",
        dateAdded: "2018-10-14"
    },
    {
        id: 18,
        title: "自杀未遂后竟然和蕾米莉亚开始交往了!?",
        author: "幻夢 ゆっくり茶番劇",
        translator: "Baby_2016",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLwnprYHAfPHaqEZqQFi2nQiPLg5Igo3mT",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6466841",
        description: "无刀可放心食用",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982deaa910d9.jpg",
        dateAdded: "2025-07-24"
    },
    {
        id: 19,
        title: "幻想入沃尔加",
        author: "ゆっくりヴォルガ",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "芙兰朵露", "十六夜咲夜", "易者", "帕秋莉", "辉夜", "藤原妹红", "古明地恋", "古明地觉", "铃仙", "魂魄妖梦", "茨木华扇", "姬海棠果", "射命丸文", "犬走椛", "洩矢诹访子", "八坂神奈子", "东风谷早苗", "二岩猯藏", "红美铃", "小恶魔", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLn5zMpk5-YR-Qzz5RcosD3oA5MbuMk23V",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6525221",
        description: "mmd和茶番剧二合一",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982deaa90602.jpg",
        dateAdded: "2024-07-31"
    },
    {
        id: 20,
        title: "拯救被欺凌男孩的天使妹妹",
        author: "シク−Siku−   ゆっくり",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "芙兰朵露", "十六夜咲夜", "洩矢诹访子", "吉吊八千慧", "博丽灵梦", "八坂神奈子", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLkONYltbNkGdPwu1CVug0NyOROBUShYqh",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6809460",
        description: "繧?▲縺上ｊ縺励※縺?▲縺ｦ縺ｭ?",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982e2f69a815.jpg",
        dateAdded: "2023-10-01"
    },
    {
        id: 21,
        title: "谈了一场如魔法般的恋爱",
        author: "幻夢 ゆっくり茶番劇",
        translator: "Baby_2016",
        tags: ["帕秋莉"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLwnprYHAfPHZ0bKlsSRE1CQYkWNYw5L6U",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6702992",
        description: "帕秋莉厨必看系列",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982e2f6802e3.jpg",
        dateAdded: "2025-09-12"
    },
    {
        id: 22,
        title: "染上色彩的恋爱始于你",
        author: "ゆっくり春",
        translator: "Baby_2016",
        tags: ["圣白莲", "命莲", "八云紫", "博丽灵梦", "露米娅", "稗田阿求", "本居小铃", "上白泽慧音", "寅丸星", "幽谷响子", "云居一轮", "村纱水蜜", "森近霖之助", "爱丽丝", "宇佐见莲子", "小恶魔", "帕秋莉", "封兽鵺", "多多良小伞", "风见幽香", "蕾米莉亚", "芙兰朵露", "藤原妹红", "铃仙", "琪露诺", "红美铃", "大妖精", "米斯蒂娅", "莉格露", "魂魄妖梦", "西行寺幽幽子", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLwsFUfY3oQWJ3GsyshggcsJbI6_X8hRD0",
        translatedUrl: "https://space.bilibili.com/499929312/lists/7221002",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982e2f69d767.jpg",
        dateAdded: "2024-08-23"
    },
    {
        id: 23,
        title: "博丽灵梦消失的那一天",
        author: "みつば【mituba】",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "东风谷早苗", "蕾米莉亚", "西行寺幽幽子", "八意永琳", "铃仙"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=y6Kwj56KTCE",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4535137",
        description: "如果你最珍视的人明天就要离世了，你会怎么做？",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982fea9ce0dc.jpg",
        dateAdded: "2021-06-07"
    },
    {
        id: 24,
        title: "满脑子黄色废料的心酱",
        author: "不知火桃",
        translator: "幻想入的Jier",
        tags: ["秦心", "丰聪耳神子"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=7_eM4AAt3XM",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4845021",
        description: "我这人啊，就是爱瞎操心",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982fea9d8c61.jpg",
        dateAdded: "2022-10-09"
    },
    {
        id: 25,
        title: "○○空间",
        author: "KOTATU",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "蕾米莉亚", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=SoOBZO_n5gU",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5078005",
        description: "想要出去就只能○○的房间",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6982feaa04b7b.jpg",
        dateAdded: "2023-11-07"
    },
    {
        id: 26,
        title: "【みるもるの家】作者的茶番剧合集",
        author: "みるもるの家",
        translator: "幻想入的Jier",
        tags: ["古明地恋", "古明地觉", "蕾米莉亚", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=t-vZgFACfmw",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4780455",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6983041b835ce.jpg",
        dateAdded: "2021-11-14"
    },
    {
        id: 27,
        title: "Super_Nakachan作者的贴贴合集",
        author: "Super_Nakachan",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "射命丸文", "蕾米莉亚", "帕秋莉", "爱丽丝", "八云紫", "古明地觉", "古明地恋", "八云紫", "摩多罗隐岐奈", "十六夜咲夜"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=NNAi4rWxy4k",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4396885",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6983041bc47bb.jpg",
        dateAdded: "2022-08-05"
    },
    {
        id: 28,
        title: "病娇芙兰对我展开了猛烈追求！？",
        author: "転生さん",
        translator: "幻想入的Jier",
        tags: ["芙兰朵露", "宇佐见莲子"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLl_rWSOGGXM8ULORk8_P5JQJEc4AIEz4W",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4409450",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6983041cde7bd.jpg",
        dateAdded: "2020-09-02"
    },
    {
        id: 29,
        title: "【月田瑞希】的桃子文茶番剧合集",
        author: "月田瑞希",
        translator: "幻想入的Jier",
        tags: ["芙兰朵露", "古明地恋", "古明地觉", "博丽灵梦", "多多良小伞", "秦心", "琪露诺", "上白泽慧音", "蕾米莉亚"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=qrRNO2w6JqE",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5117741",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/69830537aa06c.jpg",
        dateAdded: "2025-02-03"
    },
    {
        id: 30,
        title: "【東方キャラと恋愛するノベル動画ch】的茶番剧合集",
        author: "東方キャラと恋愛するノベル動画ch",
        translator: "幻想入的Jier",
        tags: ["十六夜咲夜", "古明地觉", "魂魄妖梦", "琪露诺", "蕾米莉亚"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=U_hPtTKAMlM",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5574603",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6983073da92d7.jpg",
        dateAdded: "2022-10-02"
    },
    {
        id: 31,
        title: "始于小伞的恋物语",
        author: "みとは ゆっくり製作所",
        translator: "幻想入的Jier",
        tags: ["多多良小伞", "封兽鵺", "博丽灵梦", "雾雨魔理沙", "东风谷早苗", "十六夜咲夜"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLVBIKA03FhZPjrYJAJ4Qb3bXCZAyE8jyv",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4758726",
        description: "雨爱的秘密，会一直延续~",
        thumbnail: "https://free.picui.cn/free/2026/02/04/6983081bbf01f.jpg",
        dateAdded: "2023-01-13"
    },
    {
        id: 32,
        title: "〆タケ作者的纯爱超甜合集",
        author: "〆タケ",
        translator: "幻想入的Jier",
        tags: ["蕾米莉亚", "芙兰朵露", "秦心"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=c6mxNbdWinY",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4415038",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/698308f1f0a80.jpg",
        dateAdded: "2024-08-18"
    },
    {
        id: 33,
        title: "【ゆっくり紫月】的百合向茶番剧合集",
        author: "ゆっくり紫月",
        translator: "幻想入的Jier",
        tags: ["依莉斯", "博丽灵梦"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=6KldaHy1u0I",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5409881",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/698309dceb812.jpg",
        dateAdded: "2025-03-03"
    },
    {
        id: 34,
        title: "古今西行歌枕",
        author: "森の民やむぅ",
        translator: "幻想入的Jier",
        tags: ["西行寺幽幽子", "八云紫", "魂魄妖梦"],
        isTranslated: true,
        originalUrl: "https://www.nicovideo.jp/watch/sm28681278",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5224003",
        description: "莫问来生伴谁侧，樱花落处即相逢。",
        thumbnail: "https://free.picui.cn/free/2026/02/04/69830b90345c5.jpg",
        dateAdded: "2016-04-23"
    },
    {
        id: 35,
        title: "xxx变成病娇了……？",
        author: "れくしぃちきん@ゆっくり茶番劇",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "芙兰朵露", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL3rAsEOjJPkNOjHdzZr77LpCrL1C69gKP",
        translatedUrl: "https://space.bilibili.com/87123918/lists/6936080",
        description: "想起了…",
        thumbnail: "https://free.picui.cn/free/2026/02/04/69830c59609bd.jpg",
        dateAdded: "2020-10-01"
    },
    {
        id: 36,
        title: "青梅竹马的恋恋想让我心动",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["古明地恋"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuyorGr52XSbjp9DQbJQ3mBS",
        translatedUrl: "https://www.bilibili.com/video/BV1mxdSYeE62",
        description: "恋恋可爱捏（",
        thumbnail: "https://free.picui.cn/free/2026/02/04/69830d4c75b9c.jpg",
        dateAdded: "2020-05-14"
    },
    {
        id: 37,
        title: "进来让蕾咪强控你26秒",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/shorts/S7oAsAhm0NU",
        translatedUrl: "https://www.bilibili.com/video/BV1jDdbYoEca",
        description: "蕾米可爱捏",
        thumbnail: "https://free.picui.cn/free/2026/02/04/69830dbf3a157.jpg",
        dateAdded: "2024-03-10"
    },
    {
        id: 38,
        title: "无法吃人的食人妖怪",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["露米娅", "博丽灵梦", "雾雨魔理沙", "古明地恋", "卡娜安娜贝拉尔"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOux8cq6dLe9S47gQJkk_uuZz",
        translatedUrl: "https://www.bilibili.com/video/BV1emAseZEwa",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/04/69830ec01ab5c.jpg",
        dateAdded: "2020-06-14"
    },
    {
        id: 39,
        title: "渺小之人的伟大勇气",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["琪露诺", "大妖精", "米斯蒂娅", "莉格露", "露米娅", "上白泽慧音"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuzcuFHQqi6LQQpGDJUGiTPz",
        translatedUrl: "https://www.bilibili.com/video/BV1wFRVYXE9m",
        description: "以baka小队为主角的系列~",
        thumbnail: "https://free.picui.cn/free/2026/02/04/698310463f030.jpg",
        dateAdded: "2024-03-02"
    },
    {
        id: 40,
        title: "平凡的我与、天才般的你",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["蕾米莉亚", "东风谷早苗", "芙兰朵露"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuxc9DJkmjOcEkTYfUehOCXb",
        translatedUrl: "https://www.bilibili.com/video/BV1mtPveLEjJ",
        description: "在无数重复的时间线中，我的声音定能再度围绕你左右。",
        thumbnail: "https://free.picui.cn/free/2026/02/04/698310e9572ff.jpg",
        dateAdded: "2024-08-30"
    },
    {
        id: 41,
        title: "世界上最难操作的游戏",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["雾雨魔理沙", "蕾米莉亚"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuwb0u1PD_ipY9UREG6ig5fJ",
        translatedUrl: "https://www.bilibili.com/video/BV1ZEdZY3ERs",
        description: "可以看到蕾米花式破防的一集（",
        thumbnail: "https://free.picui.cn/free/2026/02/04/698311780ffef.jpg",
        dateAdded: "2024-09-21"
    },
    {
        id: 42,
        title: "Bunny girl",
        author: "MISAKI 3518",
        translator: "寄遗忘之物于流年",
        tags: ["铃仙"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=ienoNid46dM&list=PLPIDlOi7aH3EiGs9HnU3Rg52r4j587qsI&index=6",
        translatedUrl: "https://www.bilibili.com/video/BV16A6QBCEqD/?vd_source=29215d7e01e2e3b79461f647961a787f",
        description: "与铃仙在酒吧的小故事",
        thumbnail: "https://free.picui.cn/free/2026/02/03/6981d4bbb3958.jpg",
        dateAdded: "2025-06-20"
    },
    {
        id: 43,
        title: "即使如此，帕露西依然选择当个家里蹲",
        author: "ラカルとゆっくりB",
        translator: "寄遗忘之物于流年",
        tags: ["水桥帕露西", "茨木华扇"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=LqAzlj1yJGA",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6835169",
        description: "留学回来之后，青梅竹马的帕露西居然退学了，还当了家里蹲？！",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69841acba1394.jpg",
        dateAdded: "2020-05-14"
    },
    {
        id: 44,
        title: "蛙之季",
        author: "ラカルとゆっくりB",
        translator: "寄遗忘之物于流年",
        tags: ["洩矢诹访子"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=6H-RJpUbXbE",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6859688",
        description: "。我重生了，回到了我初中一年级入学的时候，这次，我要改变我的命运，不再成为一个40岁一事无成碌碌无为的社畜",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842889d0f3b.jpg",
        dateAdded: "2019-03-15"
    },
    {
        id: 45,
        title: "女难之相的我与表姐与女性朋友",
        author: "あーる。/ aru",
        translator: "寄遗忘之物于流年",
        tags: ["绵月依姬", "绵月丰姬", "冴月麟"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLkbhAsj-moQyC4JME0vR2_OrKR2r8GNFt",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7099795",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/05/6984294e7a9cf.jpg",
        dateAdded: "2021-06-18"
    },
    {
        id: 46,
        title: "与奴隶少女觉的同居生活",
        author: "ルナ「露優」",
        translator: "寄遗忘之物于流年",
        tags: ["古明地觉", "菅牧典"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLsU0BZFJZhxU18cReRmpsGDqJD8AwDL9D",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6834497",
        description: "与可爱的奴隶少女觉开启了同居生活……",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842a173c351.jpg",
        dateAdded: "2022-07-01"
    },
    {
        id: 47,
        title: "身患恐女症的我，竟多了个义妹！？",
        author: "じぇすさんのゆっくり部屋",
        translator: "寄遗忘之物于流年",
        tags: ["多多良小伞", "物部布都", "上白泽慧音"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL3YhIU0YsQWPDaRyBdd1Owi4Fidnj6n3L",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6829056",
        description: "为了防止新的义妹进入到我家，我对自己的家进行了要塞计划，可惜被老爹直接叫停，然而当我一打开门，遇到的却是……",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842ad15237b.jpg",
        dateAdded: "2023-05-15"
    },
    {
        id: 48,
        title: "夏露露",
        author: "まったりさん",
        translator: "寄遗忘之物于流年",
        tags: ["蕾米莉亚", "多多良小伞"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcclXhofki7-qmExJa24NPwia",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7238326",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842b8505879.jpg",
        dateAdded: "2018-05-30"
    },
    {
        id: 49,
        title: "孤独的幻想入",
        author: "MISAKI 3518",
        translator: "寄遗忘之物于流年",
        tags: ["雾雨魔理沙", "博丽灵梦", "射命丸文", "十六夜咲夜", "冴月麟", "东风谷早苗", "铃仙", "河城荷取", "爱丽丝", "幻想入"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLPIDlOi7aH3Fk5iGBIjN_iBSQFUWHOrsd",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7150145",
        description: "幻想乡……真是厉害啊",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842c049c789.jpg",
        dateAdded: "2021-10-19"
    },
    {
        id: 50,
        title: "由于父母再婚，我与关系水火不容的妹红成为了家人",
        author: "かめーーとあらら",
        translator: "寄遗忘之物于流年",
        tags: ["藤原妹红"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/watch?v=oooMSfHdcbY",
        translatedUrl: "https://www.bilibili.com/video/BV1b3U7BUEpY",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842cdb6b705.jpg",
        dateAdded: "2023-11-04"
    },
    {
        id: 51,
        title: "学园里最令人畏惧的不良少女妹红，实际上似乎是个弟控呢",
        author: "ゆっくり「モナカ」",
        translator: "寄遗忘之物于流年",
        tags: ["藤原妹红", "铃仙"],
        isTranslated: true,
        originalUrl: "https://www.youtube.com/playlist?list=PLIbahIQ3NnZtSsbNwlFXr5a3RsEgfuwhX",
        translatedUrl: "https://www.bilibili.com/video/BV1J6i3BHEV6",
        description: "",
        thumbnail: "https://free.picui.cn/free/2026/02/05/69842d7f25a5e.jpg",
        dateAdded: "2023-12-10"
    }
];

const authorLinks = {
    "OKOME": "https://www.youtube.com/@OKOME-j4z",
    "ささきの茶釜": "https://www.youtube.com/@%E3%81%95%E3%81%95%E3%81%8D%E3%81%AE%E8%8C%B6%E9%87%9C",
    "ラングリィ": "https://www.youtube.com/@LANGULY",
    "まったりさん": "https://www.youtube.com/@mattarisan",
    "DAIゆっくり": "https://www.youtube.com/@_dai6935",
    "白熱の親指": "https://www.youtube.com/@%E7%99%BD%E7%86%B1%E3%81%AE%E8%A6%AA%E6%8C%87-k6g",
    "須方のさんちゃん工房": "https://www.youtube.com/@%E9%A0%88%E6%96%B9%E3%81%AE%E3%81%95%E3%82%93%E3%81%A1%E3%82%83%E3%82%93%E5%B7%A5%E6%88%BF",
    "みつば【mituba】": "https://www.youtube.com/@mituba_clover",
    "ねんねまるゆっくり": "https://www.youtube.com/@nene-yukkuri",
    "不知火桃": "https://www.youtube.com/@shiranuimomo",
    "MISAKI 3518": "https://www.youtube.com/@MISAKI-3518",
    "みるもるの家": "https://www.youtube.com/@mirumoru",
    "Super_Nakachan": "https://www.youtube.com/@SuperNakachanTV",
    "転生さん": "https://www.youtube.com/@tensei_san",
    "月田瑞希": "https://www.youtube.com/@%E6%9C%88%E7%94%B0%E7%91%9E%E5%B8%8C",
    "東方キャラと恋愛するノベル動画ch": "https://www.youtube.com/@ch-vq5tf",
    "みとは ゆっくり製作所": "https://www.youtube.com/@rinne_mitoha",
    "〆タケ": "https://www.youtube.com/@Sime-Take",
    "ゆっくり紫月": "https://www.youtube.com/@%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A%E7%B4%AB%E6%9C%88",
    "森の民やむぅ": "https://www.youtube.com/@UTA413",
    "れくしぃちきん@ゆっくり茶番劇": "https://www.youtube.com/@req4chicken",
    "アスター": "https://www.youtube.com/@%E3%82%A2%E3%82%B9%E3%82%BF%E3%83%BC-q8x",
    "KOTATU": "https://www.youtube.com/@KOTATU3118",
    "一脚踢飞毛布": "https://space.bilibili.com/33819012",
    "就是很一般": "https://space.bilibili.com/12621850",
    "Baby_2016": "https://space.bilibili.com/499929312",
    "寄遗忘之物于流年": "https://space.bilibili.com/109338384",
    "幻想入的Jier": "https://space.bilibili.com/87123918",
    "ラカルとゆっくりB": "https://www.youtube.com/@Rakaru_to_yuukuriB",
    "シク−Siku−   ゆっくり": "https://www.youtube.com/@%E3%82%B7%E3%82%AF%E3%83%BCSiku%E3%83%BC%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A",
    "ゆっくりヴォルガ": "https://www.youtube.com/@yukkuriworuga",
    "ゆっくり春": "https://www.youtube.com/@HT-qp5vx",
    "幻夢 ゆっくり茶番劇": "https://www.youtube.com/@%E5%B9%BB%E5%A4%A2-q2c",
    "あーる。/ aru": "https://www.youtube.com/@aru1496",
    "ルナ「露優」": "https://www.youtube.com/@runa_tuyu",
    "じぇすさんのゆっくり部屋": "https://www.youtube.com/@jesusan203",
    "かめーーとあらら": "https://www.youtube.com/@kame--toarara",
    "ゆっくり「モナカ」": ""
};
